# Generated by Django 5.0.4 on 2024-04-06 22:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "address1",
                    models.CharField(max_length=255, verbose_name="Endereço 1"),
                ),
                (
                    "address2",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Endereço 2"
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        choices=[("+55", "Brasil (+55)")],
                        default="+55",
                        max_length=5,
                        verbose_name="Código do País",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Telefone")),
            ],
            options={
                "verbose_name": "Clínica",
                "verbose_name_plural": "Clínicas",
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "duration",
                    models.DurationField(
                        default=datetime.timedelta(seconds=3600), verbose_name="Duração"
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano",
                "verbose_name_plural": "Planos",
            },
        ),
        migrations.CreateModel(
            name="ClinicHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("MON", "Segunda Feira"),
                            ("TUE", "Terça Feira"),
                            ("WED", "Quarta Feira"),
                            ("THU", "Quinta Feira"),
                            ("FRI", "Sexta Feira"),
                            ("SAT", "Sábado"),
                            ("SUN", "Domingo"),
                        ],
                        max_length=3,
                        verbose_name="Dia da Semana",
                    ),
                ),
                ("opening_time", models.TimeField(verbose_name="Hora de Abertura")),
                ("closing_time", models.TimeField(verbose_name="Hora de Fechamento")),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinic_hours",
                        to="clinics.clinic",
                        verbose_name="Clínica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horário da Clínica",
                "verbose_name_plural": "Horários das Clínicas",
            },
        ),
        migrations.AddField(
            model_name="clinic",
            name="plans",
            field=models.ManyToManyField(
                related_name="clinics", to="clinics.plan", verbose_name="Planos"
            ),
        ),
    ]
