# Generated by Django 5.0.3 on 2024-04-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinics", "0003_alter_clinichours_day_of_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinichours",
            name="day_of_week",
            field=models.IntegerField(
                choices=[
                    (0, "Segunda Feira"),
                    (1, "Terça Feira"),
                    (2, "Quarta Feira"),
                    (3, "Quinta Feira"),
                    (4, "Sexta Feira"),
                    (5, "Sábado"),
                    (6, "Domingo"),
                ],
                verbose_name="Dia da Semana",
            ),
        ),
    ]
