# Generated by Django 5.0.4 on 2024-05-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmado'),
        ),
    ]
