# Generated by Django 5.0.4 on 2024-06-20 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0002_alter_appointment_confirmed"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patient",
                to="patients.patient",
                verbose_name="Patiente",
            ),
            preserve_default=False,
        ),
    ]
