# Generated by Django 5.0.4 on 2024-06-21 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0003_appointment_patient"),
        ("patients", "0004_alter_patient_options_alter_patient_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patient",
                to="patients.patient",
                verbose_name="Paciente",
            ),
        ),
    ]
