# Generated by Django 5.0.4 on 2024-06-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_alter_patient_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="name",
            field=models.CharField(default=None, max_length=255, verbose_name="Name"),
            preserve_default=False,
        ),
    ]
