# Generated by Django 5.0.4 on 2024-06-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_alter_patient_options_alter_patient_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
    ]
