# Generated by Django 5.0.4 on 2024-06-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0005_alter_patient_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="id",
            field=models.BigAutoField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
